# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "authorization-rails"
  s.version = "1.0.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bill Katz; Arturo Pie"]
  s.date = "2012-03-06"
  s.description = "Rails 3 compatible rails-authorization-plugin gem"
  s.extra_rdoc_files = [
    "README.rdoc",
    "README.txt",
    "README_developers.txt"
  ]
  s.files = [
    "CHANGELOG.txt",
    "MIT-LICENSE",
    "README.rdoc",
    "README.txt",
    "README_developers.txt",
    "Rakefile",
    "UPGRADE.rdoc",
    "VERSION",
    "about.yml",
    "authorization.gemspec",
    "doc/authorization_example.gif",
    "doc/authorization_example.rb",
    "generators/role_model/USAGE",
    "generators/role_model/role_model_generator.rb",
    "generators/role_model/templates/fixtures.yml",
    "generators/role_model/templates/migration.rb",
    "generators/role_model/templates/model.rb",
    "generators/role_model/templates/role_model.rb",
    "generators/role_model/templates/role_user_model.rb",
    "generators/role_model/templates/unit_test.rb",
    "init.rb",
    "install.rb",
    "lib/authorization.rb",
    "lib/publishare/exceptions.rb",
    "lib/publishare/hardwired_roles.rb",
    "lib/publishare/identity.rb",
    "lib/publishare/object_roles_table.rb",
    "lib/publishare/parser.rb",
    "tasks/authorization_tasks.rake"
  ]
  s.homepage = "https://github.com/arturopie/rails-authorization-plugin"
  s.require_paths = [".", "lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Authoization plugin for authorizing."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

