# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{authorization}
  s.version = "1.0.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bill Katz"]
  s.date = %q{2010-11-10}
  s.description = %q{Rails 3 compatible rails-authorization-plugin gem}
  s.extra_rdoc_files = [
    "README.rdoc",
     "README.txt",
     "README_developers.txt"
  ]
  s.files = [
    "CHANGELOG.txt",
     "MIT-LICENSE",
     "README.rdoc",
     "README.txt",
     "README_developers.txt",
     "Rakefile",
     "UPGRADE.rdoc",
     "VERSION",
     "about.yml",
     "authorization.gemspec",
     "doc/authorization_example.gif",
     "doc/authorization_example.rb",
     "generators/role_model/USAGE",
     "generators/role_model/role_model_generator.rb",
     "generators/role_model/templates/fixtures.yml",
     "generators/role_model/templates/migration.rb",
     "generators/role_model/templates/model.rb",
     "generators/role_model/templates/role_model.rb",
     "generators/role_model/templates/role_user_model.rb",
     "generators/role_model/templates/unit_test.rb",
     "init.rb",
     "install.rb",
     "lib/authorization.rb",
     "lib/base.rb",
     "lib/publishare/exceptions.rb",
     "lib/publishare/hardwired_roles.rb",
     "lib/publishare/identity.rb",
     "lib/publishare/object_roles_table.rb",
     "lib/publishare/parser.rb",
     "lib/rails-authorization-plugin/railtie.rb",
     "tasks/authorization_tasks.rake"
  ]
  s.homepage = %q{https://github.com/g5search/rails-authorization-plugin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Authoization plugin for authorizing.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

